// Generated by scripts/build-client.mjs — do not edit by hand.
// Source of truth: src/client/*.ts (compiled by tsc -p tsconfig.client.json).
window.__ModuleLoader__.load({
  id: "dsh-auto-handoff",
  factory: (require) => {
    function resolveId(from, request) {
      if (request.charAt(0) !== ".") return undefined
      var parts = (from.slice(0, from.lastIndexOf("/")) + "/" + request).split("/")
      var out = []
      for (var i = 0; i < parts.length; i++) {
        var part = parts[i]
        if (part === "" || part === ".") continue
        if (part === "..") { out.pop(); continue }
        out.push(part)
      }
      return "./" + out.join("/")
    }
    var registry = {
      "./card.js": function (module, exports, require) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DATA_ATTR = exports.ROUTE_PREFIX = exports.NAMESPACE = void 0;
exports.HandoffCard = HandoffCard;
/**
 * The settings card: one plugin card inside Settings → Plugins → configurable
 * (`TASK-PLAN.md` §10.2).
 *
 * Written with `createElement` and no JSX because this file is compiled to
 * CommonJS and inlined into a browser bundle envelope, not through a JSX
 * pipeline. Every colour goes through a `--dsw-alias-*` design token; literal
 * values are fallbacks for hosts predating the alias table. The root node
 * carries `data-dsh-plugin="dsh-auto-handoff"` so skins can target it.
 */
const react_1 = require("react");
const protocol_js_1 = require("./protocol.js");
Object.defineProperty(exports, "NAMESPACE", { enumerable: true, get: function () { return protocol_js_1.NAMESPACE; } });
Object.defineProperty(exports, "ROUTE_PREFIX", { enumerable: true, get: function () { return protocol_js_1.ROUTE_PREFIX; } });
/** Stable DOM marker for skins and tests. */
exports.DATA_ATTR = 'dsh-auto-handoff';
const FIELD_LABELS = {
    autoHandoffEnabled: '启用 Token 阈值自动迁移',
    autoHandoffThreshold: '自动迁移阈值（会话累计 Token）',
    autoCompactEnabled: '启用 Token 阈值自动压缩',
    autoCompactThreshold: '自动压缩阈值（会话累计 Token）',
    rearmDeltaTokens: '重臂增量（动作成功后需再增长多少 Token）',
    maxAutoActionsPerSession: '单会话自动动作上限（1–10）',
    summaryMaxTokens: '摘要输出上限（Token）',
    stepWaitTimeoutMs: '等待 Step 完成的「偏久」提示阈值（毫秒）',
    actionDeadlineMs: '动作总时限（毫秒，到期只释放闩锁）',
    openNewSessionOnHandoff: '迁移成功后自动切换到新会话',
};
const MAIN_FIELDS = [
    'autoHandoffEnabled',
    'autoHandoffThreshold',
    'autoCompactEnabled',
    'autoCompactThreshold',
];
const ADVANCED_FIELDS = [
    'rearmDeltaTokens',
    'maxAutoActionsPerSession',
    'summaryMaxTokens',
    'stepWaitTimeoutMs',
    'actionDeadlineMs',
    'openNewSessionOnHandoff',
];
const DEFAULT_DRAFT = {
    autoHandoffEnabled: false,
    autoHandoffThreshold: 2_000_000,
    autoCompactEnabled: false,
    autoCompactThreshold: 1_500_000,
    rearmDeltaTokens: 200_000,
    maxAutoActionsPerSession: 3,
    summaryMaxTokens: 4096,
    stepWaitTimeoutMs: 900_000,
    actionDeadlineMs: 1_800_000,
    openNewSessionOnHandoff: true,
};
const S = {
    box: {
        padding: '4px 2px',
        color: 'var(--dsw-alias-label-primary, #c9d1d9)',
        fontSize: '13px',
        lineHeight: '1.6',
    },
    h2: { fontSize: '15px', fontWeight: 600, margin: '0 0 4px' },
    hint: { fontSize: '12px', color: 'var(--dsw-alias-label-secondary, #8b949e)', margin: '4px 0 0' },
    section: { marginTop: '14px' },
    row: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '12px',
        margin: '6px 0',
    },
    input: {
        width: '160px',
        padding: '3px 6px',
        background: 'var(--dsw-alias-bg-layer-1, #0d1117)',
        color: 'inherit',
        border: '1px solid var(--dsw-alias-border-l1, #30363d)',
        borderRadius: '4px',
        font: 'inherit',
    },
    button: {
        padding: '4px 10px',
        marginRight: '8px',
        borderRadius: '4px',
        border: '1px solid var(--dsw-alias-border-l1, #30363d)',
        background: 'var(--dsw-alias-bg-layer-1, #0d1117)',
        color: 'inherit',
        cursor: 'pointer',
    },
    buttonPrimary: {
        padding: '4px 10px',
        marginRight: '8px',
        borderRadius: '4px',
        border: 'none',
        background: 'var(--dsw-alias-button-primary-fill, #2f81f7)',
        color: 'var(--dsw-alias-label-primary-foreground, #ffffff)',
        cursor: 'pointer',
    },
    buttonDisabled: { opacity: 0.5, cursor: 'not-allowed' },
    bar: {
        height: '6px',
        borderRadius: '3px',
        background: 'var(--dsw-alias-bg-layer-1, #0d1117)',
        border: '1px solid var(--dsw-alias-border-l1, #30363d)',
        overflow: 'hidden',
        margin: '4px 0 0',
    },
    barFill: { height: '100%', background: 'var(--dsw-alias-button-primary-fill, #2f81f7)' },
    warn: { color: 'var(--dsw-alias-state-warning-primary, #d29922)', fontSize: '12px' },
    error: { color: 'var(--dsw-alias-state-error-primary, #f85149)', fontSize: '12px' },
    ok: { color: 'var(--dsw-alias-state-success-primary, #3fb950)', fontSize: '12px' },
    mono: { fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize: '12px' },
};
/**
 * One plugin card.
 *
 * @param props - the settings scope, the sessions service, and test seams.
 * @returns the rendered card.
 */
function HandoffCard(props) {
    const { scope, sessions } = props;
    const fetchImpl = props.fetchImpl ?? (typeof fetch === 'function' ? fetch : undefined);
    const pollMs = props.pollMs ?? 2000;
    const [, forceRender] = (0, react_1.useState)(0);
    const snapshot = scope?.getSnapshot();
    const [draft, setDraft] = (0, react_1.useState)(DEFAULT_DRAFT);
    const [dirty, setDirty] = (0, react_1.useState)(false);
    const [saving, setSaving] = (0, react_1.useState)(false);
    const [actionMessage, setActionMessage] = (0, react_1.useState)(undefined);
    const [state, setState] = (0, react_1.useState)(undefined);
    const [stateError, setStateError] = (0, react_1.useState)(undefined);
    // Bind the draft to the host value until the user edits something.
    (0, react_1.useEffect)(() => {
        if (scope === undefined)
            return undefined;
        const sync = () => {
            forceRender((value) => value + 1);
            if (dirty)
                return;
            const next = scope.getSnapshot().value;
            if (next !== undefined)
                setDraft(next);
        };
        sync();
        return scope.subscribe(sync);
    }, [scope, dirty]);
    const sessionId = sessions?.list.getSnapshot().current;
    // Poll the host state channel.
    (0, react_1.useEffect)(() => {
        if (fetchImpl === undefined || sessionId === undefined || sessionId.length === 0)
            return undefined;
        let cancelled = false;
        const tick = async () => {
            try {
                const response = await fetchImpl(`${protocol_js_1.ROUTE_PREFIX}/state?sessionId=${encodeURIComponent(sessionId)}`, { headers: { accept: 'application/json' } });
                if (!response.ok)
                    throw new Error(`HTTP ${response.status}`);
                const payload = (await response.json());
                if (!cancelled) {
                    setState(payload);
                    setStateError(undefined);
                }
            }
            catch (error) {
                if (!cancelled)
                    setStateError(error instanceof Error ? error.message : String(error));
            }
        };
        void tick();
        const timer = setInterval(() => void tick(), pollMs);
        return () => {
            cancelled = true;
            clearInterval(timer);
        };
    }, [fetchImpl, sessionId, pollMs]);
    // Switching to the new session is NOT done here: the follower in
    // `client/follow.ts` owns it, because it must run while the card is unmounted
    // (a `/handoff` typed in the chat never opens the settings tab).
    const invalid = (0, react_1.useMemo)(() => {
        if (!draft.autoHandoffEnabled || !draft.autoCompactEnabled)
            return undefined;
        if (draft.autoCompactThreshold >= draft.autoHandoffThreshold) {
            return `自动压缩阈值（${draft.autoCompactThreshold}）必须小于自动迁移阈值（${draft.autoHandoffThreshold}）。`;
        }
        return undefined;
    }, [draft]);
    const onChange = (0, react_1.useCallback)((field, value) => {
        setDirty(true);
        setDraft((previous) => ({ ...previous, [field]: value }));
    }, []);
    const onSave = (0, react_1.useCallback)(async () => {
        if (scope === undefined || invalid !== undefined)
            return;
        setSaving(true);
        try {
            for (const field of [...MAIN_FIELDS, ...ADVANCED_FIELDS]) {
                const next = draft[field];
                const current = snapshot?.value?.[field];
                if (next === current)
                    continue;
                await scope.set(field, next);
            }
            setDirty(false);
            setActionMessage('设置已保存。');
        }
        catch (error) {
            setActionMessage(`保存失败：${error instanceof Error ? error.message : String(error)}`);
        }
        finally {
            setSaving(false);
        }
    }, [scope, invalid, draft, snapshot]);
    const post = (0, react_1.useCallback)(async (action) => {
        if (fetchImpl === undefined || sessionId === undefined)
            return;
        setActionMessage(undefined);
        try {
            const response = await fetchImpl(`${protocol_js_1.ROUTE_PREFIX}/${action}`, {
                method: 'POST',
                headers: { 'content-type': 'application/json' },
                body: JSON.stringify({ sessionId }),
            });
            const payload = (await response.json());
            setActionMessage(payload.text ?? payload.error ?? (payload.ok === true ? '已受理。' : '操作失败。'));
        }
        catch (error) {
            setActionMessage(`请求失败：${error instanceof Error ? error.message : String(error)}`);
        }
    }, [fetchImpl, sessionId]);
    const children = [
        (0, react_1.createElement)('div', { key: 'title', style: S.h2 }, 'DeepSeek Harness Session Handoff'),
        (0, react_1.createElement)('p', { key: 'intro', style: S.hint }, '把当前会话的任务与进度摘要交给同工作区的新会话，继续未完成的任务。迁移不会硬中断正在运行的 Step 或 Tool Call。'),
    ];
    if (scope === undefined) {
        children.push((0, react_1.createElement)('p', { key: 'noscope', style: S.warn }, '设置服务不可用：无法读写本插件的设置。'));
    }
    else if (snapshot?.status === 'unavailable') {
        children.push((0, react_1.createElement)('p', { key: 'unavailable', style: S.warn }, '设置服务未暴露本命名空间；设置仅在本次会话内有效。'));
    }
    // ---- primary settings ----------------------------------------------------
    children.push((0, react_1.createElement)('div', { key: 'main', style: S.section }, (0, react_1.createElement)('div', { style: S.h2 }, '主设置'), ...MAIN_FIELDS.map((field) => renderField(field, draft, onChange)), invalid === undefined ? null : (0, react_1.createElement)('p', { key: 'invalid', style: S.error }, invalid)));
    // ---- status --------------------------------------------------------------
    children.push((0, react_1.createElement)('div', { key: 'status', style: S.section }, (0, react_1.createElement)('div', { style: S.h2 }, '状态'), ...renderStatus(state, stateError)));
    // ---- advanced ------------------------------------------------------------
    children.push((0, react_1.createElement)('div', { key: 'advanced', style: S.section }, (0, react_1.createElement)('div', { style: S.h2 }, '高级设置'), ...ADVANCED_FIELDS.map((field) => renderField(field, draft, onChange)), (0, react_1.createElement)('div', { style: { marginTop: '8px' } }, (0, react_1.createElement)('button', {
        type: 'button',
        style: invalid !== undefined || saving ? { ...S.buttonPrimary, ...S.buttonDisabled } : S.buttonPrimary,
        disabled: invalid !== undefined || saving,
        onClick: () => void onSave(),
    }, saving ? '保存中…' : '保存设置'), dirty ? (0, react_1.createElement)('span', { style: S.hint }, '有未保存的修改') : null)));
    // ---- actions -------------------------------------------------------------
    children.push((0, react_1.createElement)('div', { key: 'actions', style: S.section }, (0, react_1.createElement)('div', { style: S.h2 }, '操作'), (0, react_1.createElement)('div', null, (0, react_1.createElement)('button', {
        type: 'button',
        style: fetchImpl === undefined || sessionId === undefined ? { ...S.button, ...S.buttonDisabled } : S.button,
        disabled: fetchImpl === undefined || sessionId === undefined,
        onClick: () => void post('handoff'),
    }, '立即迁移'), (0, react_1.createElement)('button', {
        type: 'button',
        style: fetchImpl === undefined || sessionId === undefined ? { ...S.button, ...S.buttonDisabled } : S.button,
        disabled: fetchImpl === undefined || sessionId === undefined,
        onClick: () => void post('cancel'),
    }, '取消'), (0, react_1.createElement)('button', {
        type: 'button',
        style: fetchImpl === undefined || sessionId === undefined ? { ...S.button, ...S.buttonDisabled } : S.button,
        disabled: fetchImpl === undefined || sessionId === undefined,
        onClick: () => void post('retry'),
    }, '重试')), actionMessage === undefined ? null : (0, react_1.createElement)('p', { key: 'action-message', style: S.hint }, actionMessage)));
    return (0, react_1.createElement)('div', { style: S.box, 'data-dsh-plugin': exports.DATA_ATTR, 'data-dsh-surface': 'settings-modal' }, ...children);
}
function renderField(field, draft, onChange) {
    const label = FIELD_LABELS[field];
    const value = draft[field];
    if (typeof value === 'boolean') {
        return (0, react_1.createElement)('label', { key: field, style: S.row, 'data-dsh-part': 'field' }, (0, react_1.createElement)('span', null, label), (0, react_1.createElement)('input', {
            type: 'checkbox',
            checked: value,
            'data-dsh-field': field,
            onChange: (event) => onChange(field, event.target.checked),
        }));
    }
    return (0, react_1.createElement)('label', { key: field, style: S.row, 'data-dsh-part': 'field' }, (0, react_1.createElement)('span', null, label), (0, react_1.createElement)('input', {
        type: 'number',
        min: 0,
        step: 1,
        value: String(value),
        style: S.input,
        'data-dsh-field': field,
        onChange: (event) => {
            const parsed = Number(event.target.value);
            onChange(field, Number.isFinite(parsed) ? Math.trunc(parsed) : 0);
        },
    }));
}
function renderStatus(state, stateError) {
    if (stateError !== undefined && state === undefined) {
        return [(0, react_1.createElement)('p', { key: 'nochannel', style: S.warn }, `状态通道不可用：${stateError}`)];
    }
    if (state === undefined) {
        return [(0, react_1.createElement)('p', { key: 'loading', style: S.hint }, '正在读取状态…')];
    }
    const sourceLabel = state.tokenSource === 'exact' ? '精确' : state.tokenSource === 'estimated' ? '估算' : '不可用';
    const threshold = state.thresholds.handoff;
    const ratio = threshold > 0 ? Math.min(1, Math.max(0, state.tokens / threshold)) : 0;
    const rows = [
        (0, react_1.createElement)('div', { key: 'tokens', style: S.mono }, `会话累计 Token：${state.tokens}（${sourceLabel}）`),
        (0, react_1.createElement)('div', { key: 'bar', style: S.bar }, (0, react_1.createElement)('div', { style: { ...S.barFill, width: `${Math.round(ratio * 100)}%` } })),
        (0, react_1.createElement)('div', { key: 'phase', style: S.hint }, `阶段：${state.phaseLabel}${state.stopRequested ? '（已持有停止闩锁）' : ''}${state.atBoundary ? '（已到达 Step 边界）' : ''}`),
        (0, react_1.createElement)('div', { key: 'thresholds', style: S.hint }, `阈值：迁移 ${state.autoHandoffEnabled ? state.thresholds.handoff : '未启用'} / 压缩 ${state.autoCompactEnabled ? state.thresholds.compact : '未启用'}；本会话自动动作 ${state.autoActions}/${state.maxAutoActionsPerSession}`),
        (0, react_1.createElement)('div', { key: 'persistence', style: S.hint }, state.persistence === 'host' ? '设置持久化：Host（写入设置文件）' : '设置持久化：内存（重启后恢复默认）'),
    ];
    if (state.warnings.length > 0) {
        rows.push((0, react_1.createElement)('p', { key: 'warnings', style: S.warn }, state.warnings.join(' ')));
    }
    if (state.retired) {
        rows.push((0, react_1.createElement)('p', { key: 'retired', style: S.hint }, '本会话已退休：迁移完成后不再处理新任务。'));
    }
    if (state.lastResult !== undefined) {
        rows.push((0, react_1.createElement)('p', { key: 'last', style: state.lastResult.outcome === 'completed' ? S.ok : S.error }, `最近一次动作：${state.lastResult.text}`));
    }
    if (state.progress.length > 0) {
        rows.push((0, react_1.createElement)('div', { key: 'progress', style: { ...S.hint, ...S.mono } }, ...state.progress.slice(-5).map((line, index) => (0, react_1.createElement)('div', { key: `line-${index}` }, line))));
    }
    return rows;
}
exports.default = HandoffCard;
      },
      "./follow.js": function (module, exports, require) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_FOLLOW_ATTEMPTS = exports.DEFAULT_FOLLOW_INTERVAL_MS = void 0;
exports.startHandoffFollower = startHandoffFollower;
/**
 * The always-on browser follower: when the Host reports that a migration
 * finished for the session on screen, re-read the list and switch to the new
 * session (`TASK-PLAN.md` §10.4).
 *
 * Two facts shape this module, both learned from a real `/handoff` run whose new
 * session the user could not find:
 *
 * 1. The switch cannot live in the settings card. It used to: the card polled
 *    the Host state channel and called `sessions.open()`. But the card only
 *    exists while the settings tab is mounted, and `/handoff` is normally typed
 *    in the chat — so the watcher was not running at all and the migration
 *    completed with no navigation. `apply()` starts this follower instead, so it
 *    is live for every page.
 *
 * 2. A freshly created session is announced to the browser as *blank*: the Host
 *    emits `api-session/added` with the summary it has at `session/created`
 *    time, when the log holds nothing but its header, and the client's list
 *    store has no later event that clears that bit — only a list re-read does
 *    (`applySessionListMetadata` clears `blank` on `turn/start`, and the client
 *    forwards neither that event nor a re-pull). The workspace browser hides
 *    blank rows unless they are the current selection, so `refresh()` is what
 *    makes the new session visible at all, and `open()` alone would switch to a
 *    row the sidebar still refuses to show.
 *
 * The baseline rule keeps the follower from hijacking a page load: a target that
 * is already recorded the first time a session is observed is history, not news.
 * Only a transition from "no new session" to "new session" switches away.
 */
const protocol_js_1 = require("./protocol.js");
/** How often the Host state channel is polled. */
exports.DEFAULT_FOLLOW_INTERVAL_MS = 2_000;
/**
 * How many polls one target gets before the follower gives up.
 *
 * The guard exists for the honest case where the brief never starts a turn: the
 * row then stays blank, the sidebar keeps hiding it, and retrying forever would
 * only re-pull the whole list every two seconds.
 */
exports.DEFAULT_FOLLOW_ATTEMPTS = 12;
/**
 * Start watching for completed migrations.
 *
 * @param options - the sessions service, a fetch implementation, and test seams.
 * @returns a handle whose `stop()` releases the interval.
 */
function startHandoffFollower(options) {
    const intervalMs = options.intervalMs ?? exports.DEFAULT_FOLLOW_INTERVAL_MS;
    const maxAttempts = options.maxAttempts ?? exports.DEFAULT_FOLLOW_ATTEMPTS;
    /**
     * Last target *concluded* per session, so "already there" never switches.
     *
     * A target is only recorded here once it has been opened, deliberately
     * skipped, or given up on. Recording it any earlier would make the retry path
     * below unreachable: the very next poll would compare equal and return before
     * re-reading the list.
     */
    const observed = new Map();
    /** Targets already acted on, or given up on. */
    const settled = new Set();
    const attempts = new Map();
    let stopped = false;
    let inFlight = false;
    const report = (error) => {
        options.onError?.(error instanceof Error ? error.message : String(error));
    };
    const tick = async () => {
        const sessions = options.sessions;
        const fetchImpl = options.fetchImpl;
        if (stopped || inFlight || sessions === undefined || fetchImpl === undefined)
            return;
        const current = sessions.list.getSnapshot().current;
        if (current === undefined || current.length === 0)
            return;
        inFlight = true;
        try {
            const response = await fetchImpl(`${protocol_js_1.ROUTE_PREFIX}/state?sessionId=${encodeURIComponent(current)}`, { headers: { accept: 'application/json' } });
            if (!response.ok)
                return;
            const state = (await response.json());
            const target = state.newSessionId;
            if (!observed.has(current)) {
                // First sighting of this session: the target it already carries predates
                // this page, so it is context for the user, not a reason to navigate.
                observed.set(current, target);
                if (target !== undefined)
                    settled.add(target);
                return;
            }
            if (observed.get(current) === target)
                return;
            if (target === undefined) {
                // The record carries no replacement session (yet, or any more). Nothing
                // to navigate to, and the session may still gain one — remember only
                // the absence.
                observed.set(current, target);
                return;
            }
            if (state.openNewSessionOnHandoff !== true) {
                // The user turned the switch off: the target is news, but not for us.
                observed.set(current, target);
                return;
            }
            if (settled.has(target)) {
                observed.set(current, target);
                return;
            }
            const attempt = (attempts.get(target) ?? 0) + 1;
            attempts.set(target, attempt);
            if (attempt > maxAttempts) {
                settled.add(target);
                observed.set(current, target);
                return;
            }
            await sessions.refresh();
            const row = sessions.list.getSnapshot().byId?.[target];
            // Not listed yet, or still blank: the sidebar would not show it, so wait
            // for the next poll instead of switching to an invisible session. The
            // target stays unrecorded so that next poll really does retry.
            if (row === undefined || row.blank === true)
                return;
            // The page may have been disposed while the list was re-read; a stopped
            // follower must not navigate.
            if (stopped)
                return;
            settled.add(target);
            observed.set(current, target);
            sessions.open(target);
        }
        catch (error) {
            report(error);
        }
        finally {
            inFlight = false;
        }
    };
    void tick();
    const timer = setInterval(() => void tick(), intervalMs);
    return {
        stop: () => {
            stopped = true;
            clearInterval(timer);
        },
    };
}
      },
      "./index.js": function (module, exports, require) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.inject = exports.name = void 0;
exports.apply = apply;
/**
 * Browser half of `dsh-auto-handoff`.
 *
 * The Host registers the `dsh-auto-handoff` settings namespace; this half
 * registers the matching card under the same key in the `settings.plugin.item`
 * slot, which is the seat the plugin configuration tab dispatches
 * (`TASK-PLAN.md` §10.1), and starts the always-on migration follower (§10.4).
 *
 * `inject` must list every service `apply()` reads. Cordis resolves services
 * through a proxy whose `get` trap throws
 * `cannot get property "<name>" without inject` for any service the fiber does
 * not declare — even when the provider IS active in the same graph. A sibling
 * bundle provides each one (`slots` ← ui-slots, `settingsScope` ← ui-settings,
 * `sessions` ← the session controller), so the boot order is not ours to
 * assume; declaring them lets Cordis start the fiber only once all three are
 * live, which is also what `settingsScope.bind()` needs (it hangs its disposer
 * on the calling fiber). The card still degrades on its own when the Host does
 * not expose this namespace.
 */
const react_1 = require("react");
const card_js_1 = require("./card.js");
const follow_js_1 = require("./follow.js");
const protocol_js_1 = require("./protocol.js");
/** Loader diagnostic name; matches the Host half. */
exports.name = 'dsh-auto-handoff';
/** Every service `apply()` reads; see the module doc for why all are declared. */
exports.inject = ['slots', 'settingsScope', 'sessions'];
/**
 * Register the plugin card and start the migration follower.
 *
 * @param ctx - the browser plugin context; `inject` guarantees every service
 *   read below is active.
 */
function apply(ctx) {
    const slots = ctx.slots;
    const sessions = ctx.sessions;
    // The follower runs for the whole page, not for one mounted component: it is
    // what navigates after a `/handoff` typed in the chat.
    ctx.effect(() => {
        const follower = (0, follow_js_1.startHandoffFollower)({
            sessions,
            fetchImpl: typeof fetch === 'function' ? fetch.bind(globalThis) : undefined,
            onError: (message) => console.warn(`[dsh-auto-handoff] 自动切换轮询失败：${message}`),
        });
        return () => follower.stop();
    }, 'dsh-auto-handoff: handoff follower');
    if (slots === undefined) {
        console.warn('[dsh-auto-handoff] slots 服务不可用，设置卡未注册。');
        return;
    }
    const scope = ctx.settingsScope.bind({ namespace: protocol_js_1.NAMESPACE });
    ctx.effect(() => {
        slots.inject('settings.plugin.item', () => slots.register({ name: 'settings.plugin.item', key: protocol_js_1.NAMESPACE }, () => (0, react_1.createElement)(card_js_1.HandoffCard, { scope, sessions })));
    }, 'dsh-auto-handoff: settings card');
}
exports.default = { name: exports.name, inject: exports.inject, apply };
      },
      "./protocol.js": function (module, exports, require) {
"use strict";
/**
 * The browser half's wire contract and the narrow service shapes both halves of
 * the UI code share (`TASK-PLAN.md` §10).
 *
 * This module is deliberately free of React: the settings card and the
 * always-on follower are two independent consumers of the same payload, and the
 * follower is started by `apply()`, long before any card is mounted. Keeping the
 * types here is also what lets the follower be unit-tested without a renderer.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ROUTE_PREFIX = exports.NAMESPACE = void 0;
/** Settings namespace; must match the Host registration. */
exports.NAMESPACE = 'dsh-auto-handoff';
/** HTTP prefix registered by the Host half. */
exports.ROUTE_PREFIX = '/dsh-auto-handoff';
      },
    }
    var cache = {}
    function load(id) {
      if (cache[id]) return cache[id].exports
      var factory = registry[id]
      if (!factory) throw new Error("client module not found: " + id)
      var module = { exports: {} }
      cache[id] = module
      factory(module, module.exports, function (request) {
        var nested = resolveId(id, request)
        return nested === undefined ? require(request) : load(nested)
      })
      return module.exports
    }
    return load("./index.js")
  },
})
