/**
 * Wrap the compiled client half into the DSH browser bundle envelope.
 *
 * The browser module table executes a plugin bundle only when the script calls
 * `window.__ModuleLoader__.load({ id, factory })`; the factory receives a
 * synchronous `require` bound to the module table and returns the plugin's
 * exports. `tsc -p tsconfig.client.json` emits plain CommonJS into
 * `.build/client`, so this script only needs to inline those modules into a
 * tiny lazy registry and hand the entry module's exports back — no third-party
 * bundler, and the client sources stay real, type-checked TypeScript.
 *
 * Module ids are relative specifiers exactly as `tsc` emitted them
 * (`./card.js`); every other specifier (`react`, …) is delegated to the
 * loader's own `require`.
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, posix, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const srcDir = join(root, '.build', 'client')
const outFile = join(root, 'lib', 'client.js')
const pluginId = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).name

/** Collect every emitted `.js` module, keyed by its bundle-relative id. */
function collect(dir) {
  const found = new Map()
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      for (const [key, value] of collect(full)) found.set(key, value)
      continue
    }
    if (!entry.endsWith('.js')) continue
    const id = './' + relative(srcDir, full).split(sep).join(posix.sep)
    found.set(id, readFileSync(full, 'utf8').replace(/\n+$/, ''))
  }
  return found
}

const modules = collect(srcDir)
const entry = './index.js'
if (!modules.has(entry)) {
  throw new Error(`client build: missing entry module ${entry} under ${srcDir}`)
}

const lines = [
  '// Generated by scripts/build-client.mjs — do not edit by hand.',
  '// Source of truth: src/client/*.ts (compiled by tsc -p tsconfig.client.json).',
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pluginId)},`,
  '  factory: (require) => {',
  '    function resolveId(from, request) {',
  '      if (request.charAt(0) !== ".") return undefined',
  '      var parts = (from.slice(0, from.lastIndexOf("/")) + "/" + request).split("/")',
  '      var out = []',
  '      for (var i = 0; i < parts.length; i++) {',
  '        var part = parts[i]',
  '        if (part === "" || part === ".") continue',
  '        if (part === "..") { out.pop(); continue }',
  '        out.push(part)',
  '      }',
  '      return "./" + out.join("/")',
  '    }',
  '    var registry = {',
]

for (const [id, code] of modules) {
  lines.push(`      ${JSON.stringify(id)}: function (module, exports, require) {`)
  lines.push(code)
  lines.push('      },')
}

lines.push(
  '    }',
  '    var cache = {}',
  '    function load(id) {',
  '      if (cache[id]) return cache[id].exports',
  '      var factory = registry[id]',
  '      if (!factory) throw new Error("client module not found: " + id)',
  '      var module = { exports: {} }',
  '      cache[id] = module',
  '      factory(module, module.exports, function (request) {',
  '        var nested = resolveId(id, request)',
  '        return nested === undefined ? require(request) : load(nested)',
  '      })',
  '      return module.exports',
  '    }',
  `    return load(${JSON.stringify(entry)})`,
  '  },',
  '})',
  '',
)

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, lines.join('\n'), 'utf8')
rmSync(srcDir, { recursive: true, force: true })
console.log(`[dsh-auto-handoff] wrote ${relative(root, outFile)} from ${modules.size} module(s)`)
